name: Deploy App

on:
  push:
    branches:
      - main # Deploys to production
      - staging # Deploys to staging

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Extract Version from package.json
        id: get_version
        run: echo "VERSION=$(node -p 'require("./package.json").version')" >> $GITHUB_OUTPUT

      - name: Inject Version into files
        run: |
          sed -i "s/{{APP_VERSION}}/${{ steps.get_version.outputs.VERSION }}/g" index.html
          sed -i "s/{{APP_VERSION}}/${{ steps.get_version.outputs.VERSION }}/g" sw.js

      - name: Install Dependencies
        if: github.ref == 'refs/heads/main'
        run: npm ci

      - name: Install Playwright Browsers
        if: github.ref == 'refs/heads/main'
        run: npx playwright install --with-deps

      - name: Run Tests
        if: github.ref == 'refs/heads/main'
        run: npm run test

      - name: Determine Deployment Path
        id: deploy_path
        run: |
          echo "DEBUG: GITHUB_REF is $GITHUB_REF"
          if [[ "$GITHUB_REF" == "refs/heads/main" ]]; then
            echo "DEST_DIR=." >> $GITHUB_OUTPUT
          else
            echo "DEST_DIR=staging" >> $GITHUB_OUTPUT
          fi

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./
          destination_dir: ${{ steps.deploy_path.outputs.DEST_DIR }}
